### ISSUE TITLE
Issue in "Primer"

### ISSUE THREAD

**Issue by takeiga** [lmdu/krait#6]
After SSR search, I conducted Primer design, but facing the following error in both linux (Ubuntu) and Windows 10 (64bit). The result is truncated in hundred loci or a thousand, even I submitted few million loci. Also I could not export results after indication of this error.
Thx.

Traceback (most recent call last):
  File "workers.py" line 82, in run
  File "workers.py" line 413, in process
  File "db.py", line 157, in begin
  File "db.py", line 134, in query
  File "c:\users\appveyor\appdata\local\temp\1\pip-req-build-pfvgtr\src\cursor.c", line 236, in resetcursor SQLError: SQLError: cannot start a transaction within a transaction

**Comment by lmdu** [comment]
In our new version, this error has been fixed. This error may be caused by previous unfinished task.
